spring.application.name=ProyectoE1

server.port=9002

# Configurar la conexion a SQLite
spring.datasource.url=jdbc:sqlite:proyecto.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Indica si debe mostrar el log de las consultas sql ejecutadas
spring.jpa.show-sql=true

# Configurar Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.data.jpa.repositories.enabled=true
